### PR TITLE
update markdown - sybase iq not supported

### PR DESCRIPTION
**Pull request by exa-danilo**
We discovered that the virtual schema implementation does not support the use of the Sybase IQ DB. This is something we would like to highlight in here for future sybase implementations.

### CODE REVIEW

**Comment by shib-maximalist** [comment]
Thanks!

**Comment by morazow** [comment]
Hello @exa-danilo,
Thanks for the feedback and pull request!
Could you please move it to the README file (after first paragraph)? It would be more visible there than user guide.

**Comment by exa-danilo** [comment]
Hey there, can we have it in both .md to make sure everybody sees it?

**Comment by exa-danilo** [comment]
applied the changes

**Review by morazow — APPROVED** [review]
Looks good!

**Pull request merged**
